# Generated by Django 5.1.4 on 2025-04-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecodeli_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('livreur', 'Livreur'), ('client', 'Client'), ('commercant', 'Commerçant'), ('prestataire', 'Prestataire de services')], default='client', help_text='Sélectionnez le type de compte utilisateur', max_length=20, verbose_name="type d'utilisateur"),
        ),
    ]
