# Generated by Django 5.1.4 on 2025-04-15 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificatifType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('description', models.TextField(verbose_name='description')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='obligatoire')),
            ],
            options={
                'verbose_name': 'type de justificatif',
                'verbose_name_plural': 'types de justificatifs',
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(verbose_name='date de début')),
                ('date_fin', models.DateTimeField(verbose_name='date de fin')),
                ('livreur', models.ForeignKey(limit_choices_to={'user_type': 'livreur'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to=settings.AUTH_USER_MODEL, verbose_name='livreur')),
            ],
            options={
                'verbose_name': 'disponibilité',
                'verbose_name_plural': 'disponibilités',
            },
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='justificatifs/', verbose_name='fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="date d'upload")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='statut')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='commentaire administrateur')),
                ('livreur', models.ForeignKey(limit_choices_to={'user_type': 'livreur'}, on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to=settings.AUTH_USER_MODEL, verbose_name='livreur')),
                ('type_justificatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livreur.justificatiftype', verbose_name='type de justificatif')),
            ],
            options={
                'verbose_name': 'justificatif',
                'verbose_name_plural': 'justificatifs',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_depart', models.CharField(max_length=255, verbose_name='adresse de départ')),
                ('adresse_arrivee', models.CharField(max_length=255, verbose_name="adresse d'arrivée")),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='date de demande')),
                ('date_livraison_prevue', models.DateTimeField(verbose_name='date de livraison prévue')),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True, verbose_name='date de livraison réelle')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de confirmation'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('commission_plateforme', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='commission plateforme')),
                ('poids', models.FloatField(blank=True, null=True, verbose_name='poids (kg)')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='volume (m³)')),
                ('commentaire_client', models.TextField(blank=True, verbose_name='commentaire client')),
                ('commentaire_livreur', models.TextField(blank=True, verbose_name='commentaire livreur')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('livreur', models.ForeignKey(limit_choices_to={'user_type': 'livreur'}, on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to=settings.AUTH_USER_MODEL, verbose_name='livreur')),
            ],
            options={
                'verbose_name': 'livraison',
                'verbose_name_plural': 'livraisons',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('reference', models.CharField(max_length=100, verbose_name='référence')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='statut')),
                ('livraisons', models.ManyToManyField(related_name='paiements', to='livreur.livraison', verbose_name='livraisons')),
                ('livreur', models.ForeignKey(limit_choices_to={'user_type': 'livreur'}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL, verbose_name='livreur')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
            },
        ),
        migrations.CreateModel(
            name='ProfilLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField(blank=True, verbose_name='adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='code postal')),
                ('numero_immatriculation', models.CharField(blank=True, max_length=50, verbose_name="numéro d'immatriculation")),
                ('description_vehicule', models.TextField(blank=True, verbose_name='description du véhicule')),
                ('rayon_action', models.IntegerField(default=20, verbose_name="rayon d'action (km)")),
                ('capacite_poids_max', models.FloatField(default=10, verbose_name='capacité de poids maximale (kg)')),
                ('capacite_volume_max', models.FloatField(default=0.5, verbose_name='capacité de volume maximale (m³)')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('disponible', models.BooleanField(default=True, verbose_name='disponible')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_livreur', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'profil livreur',
                'verbose_name_plural': 'profils livreurs',
            },
        ),
        migrations.CreateModel(
            name='TrajetAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_depart', models.CharField(max_length=255, verbose_name='adresse de départ')),
                ('ville_depart', models.CharField(max_length=100, verbose_name='ville de départ')),
                ('code_postal_depart', models.CharField(max_length=10, verbose_name='code postal de départ')),
                ('adresse_arrivee', models.CharField(max_length=255, verbose_name="adresse d'arrivée")),
                ('ville_arrivee', models.CharField(max_length=100, verbose_name="ville d'arrivée")),
                ('code_postal_arrivee', models.CharField(max_length=10, verbose_name="code postal d'arrivée")),
                ('date_depart', models.DateTimeField(verbose_name='date de départ')),
                ('date_arrivee', models.DateTimeField(verbose_name="date d'arrivée")),
                ('capacite_poids', models.FloatField(verbose_name='capacité de poids disponible (kg)')),
                ('capacite_volume', models.FloatField(verbose_name='capacité de volume disponible (m³)')),
                ('commentaire', models.TextField(blank=True, verbose_name='commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('complete', 'Complété'), ('annule', 'Annulé')], default='actif', max_length=20, verbose_name='statut')),
                ('livreur', models.ForeignKey(limit_choices_to={'user_type': 'livreur'}, on_delete=django.db.models.deletion.CASCADE, related_name='trajets_annonces', to=settings.AUTH_USER_MODEL, verbose_name='livreur')),
            ],
            options={
                'verbose_name': 'trajet annoncé',
                'verbose_name_plural': 'trajets annoncés',
            },
        ),
        migrations.AddField(
            model_name='livraison',
            name='trajet_annonce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='livreur.trajetannonce', verbose_name='trajet annoncé'),
        ),
    ]
