# Generated by Django 5.1.4 on 2025-04-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificatif',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/', verbose_name='fichier'),
        ),
    ]
