# Generated by Django 5.1.4 on 2025-04-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0002_alter_justificatif_fichier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='montant',
        ),
    ]
