# Generated by Django 5.1.4 on 2025-04-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0003_remove_paiement_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=10)),
            ],
        ),
    ]
