# Generated by Django 5.1.4 on 2025-04-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0004_visiteur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visiteur',
        ),
    ]
