# Generated by Django 5.1.4 on 2025-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0005_delete_visiteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajetannonce',
            name='capacite_poids',
            field=models.FloatField(blank=True, verbose_name='capacité de poids disponible (kg)'),
        ),
        migrations.AlterField(
            model_name='trajetannonce',
            name='capacite_volume',
            field=models.FloatField(blank=True, verbose_name='capacité de volume disponible (m³)'),
        ),
    ]
