# Generated by Django 5.1.4 on 2025-06-07 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0006_alter_trajetannonce_capacite_poids_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='adresse_arrivee',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='adresse_depart',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='client',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='date_demande',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='date_livraison_prevue',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='date_livraison_reelle',
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commentaire_client',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='commentaire client'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commentaire_livreur',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='commentaire livreur'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='commission_plateforme',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='commission plateforme'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to=settings.AUTH_USER_MODEL, verbose_name='livreur'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='poids',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='poids (kg)'),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='volume',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='volume (m³)'),
        ),
        migrations.AlterField(
            model_name='trajetannonce',
            name='livreur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets_annonces', to=settings.AUTH_USER_MODEL, verbose_name='livreur'),
        ),
        migrations.AlterField(
            model_name='trajetannonce',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('selected', 'Selected'), ('annule', 'Annulé')], default='actif', max_length=20, verbose_name='statut'),
        ),
    ]
