# Generated by Django 5.1.4 on 2025-06-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0007_remove_livraison_adresse_arrivee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='commission_plateforme',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='volume',
        ),
        migrations.AddField(
            model_name='trajetannonce',
            name='commission_plateforme',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='commission plateforme'),
        ),
        migrations.AddField(
            model_name='trajetannonce',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='montant'),
        ),
        migrations.AddField(
            model_name='trajetannonce',
            name='poids',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='poids (kg)'),
        ),
        migrations.AddField(
            model_name='trajetannonce',
            name='volume',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='volume (m³)'),
        ),
    ]
