# Generated by Django 5.1.4 on 2025-06-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0008_remove_livraison_commission_plateforme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajetannonce',
            name='commission_plateforme',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=10, null=True, verbose_name='commission plateforme'),
        ),
    ]
