# Generated by Django 5.1.4 on 2025-06-08 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0009_alter_trajetannonce_commission_plateforme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajetannonce',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='trajetannonce',
            name='volume',
        ),
    ]
