# Generated by Django 5.1.4 on 2025-06-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0010_remove_trajetannonce_poids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetannonce',
            name='photo_produit',
            field=models.ImageField(blank=True, null=True, upload_to='livraisons/', verbose_name='photo du produit'),
        ),
    ]
