# Generated by Django 5.1.4 on 2025-07-06 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livreur', '0011_trajetannonce_photo_produit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes_livraisons', to=settings.AUTH_USER_MODEL, verbose_name='client'),
        ),
        migrations.CreateModel(
            name='CompteLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_titulaire', models.CharField(max_length=100, verbose_name='Nom du titulaire')),
                ('stripe_account_id', models.CharField(blank=True, max_length=200, verbose_name='ID Compte Stripe')),
                ('stripe_verified', models.BooleanField(default=False, verbose_name='Compte vérifié')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('livreur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_livreur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='numéro')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='taux TVA')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant TTC')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_echeance', models.DateTimeField(verbose_name="date d'échéance")),
                ('date_paiement_client', models.DateTimeField(blank=True, null=True, verbose_name='date paiement client')),
                ('date_liberation_fonds', models.DateTimeField(blank=True, null=True, verbose_name='date libération fonds')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('fonds_bloques', 'Fonds bloqués (séquestre)'), ('en_attente_confirmation', 'En attente de confirmation'), ('fonds_liberes', 'Fonds libérés au livreur'), ('litige', 'En litige'), ('rembourse', 'Remboursé au client'), ('annulee', 'Annulée')], default='en_attente', max_length=25, verbose_name='statut')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Payment Intent Stripe')),
                ('confirmation_livraison_livreur', models.BooleanField(default=False, verbose_name='Livraison confirmée par livreur')),
                ('confirmation_reception_client', models.BooleanField(default=False, verbose_name='Réception confirmée par client')),
                ('date_confirmation_livreur', models.DateTimeField(blank=True, null=True, verbose_name='Date confirmation livreur')),
                ('date_confirmation_client', models.DateTimeField(blank=True, null=True, verbose_name='Date confirmation client')),
                ('delai_auto_liberation', models.DateTimeField(blank=True, null=True, verbose_name='Délai auto-libération')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
                ('livraison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='livreur.livraison')),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('type_notification', models.CharField(choices=[('paiement', 'Paiement'), ('livraison', 'Livraison'), ('confirmation', 'Confirmation'), ('litige', 'Litige'), ('liberation', 'Libération de fonds')], max_length=20, verbose_name='type')),
                ('lue', models.BooleanField(default=False, verbose_name='lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date création')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PaiementLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant brut')),
                ('commission_plateforme', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Commission plateforme')),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant net versé')),
                ('stripe_transfer_id', models.CharField(max_length=200, verbose_name='ID Transfer Stripe')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('complete', 'Terminé'), ('echec', 'Échec')], default='en_cours', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement_livreur', to='livreur.facture')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_recus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
