# Generated by Django 5.1.4 on 2025-04-24 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('adresse_depart', models.CharField(max_length=255, verbose_name='adresse de départ')),
                ('adresse_arrivee', models.CharField(max_length=255, verbose_name="adresse d'arrivée")),
                ('date_livraison_souhaitee', models.DateTimeField(verbose_name='date de livraison souhaitée')),
                ('poids', models.FloatField(blank=True, null=True, verbose_name='poids (kg)')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='volume (m³)')),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='budget maximum')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='ouverte', max_length=20, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'verbose_name': 'annonce client',
                'verbose_name_plural': 'annonces clients',
            },
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(max_length=100, verbose_name='type de service')),
                ('date_service', models.DateTimeField(verbose_name='date du service')),
                ('adresse', models.CharField(max_length=255, verbose_name='adresse')),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tarif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('commentaire_client', models.TextField(blank=True, verbose_name='commentaire client')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_services', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('prestataire', models.ForeignKey(limit_choices_to={'user_type': 'prestataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='services_reserves', to=settings.AUTH_USER_MODEL, verbose_name='prestataire')),
            ],
            options={
                'verbose_name': 'réservation de service',
                'verbose_name_plural': 'réservations de services',
            },
        ),
    ]
