# Generated by Django 5.1.4 on 2025-05-07 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresseLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_adresse', models.CharField(max_length=50, verbose_name="Nom de l'adresse")),
                ('destinataire', models.CharField(max_length=100, verbose_name='Nom du destinataire')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('complement_adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name="Complément d'adresse")),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('instructions_speciales', models.TextField(blank=True, null=True, verbose_name='Instructions spéciales')),
                ('par_defaut', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Adresse de livraison',
                'verbose_name_plural': 'Adresses de livraison',
            },
        ),
        migrations.AlterModelOptions(
            name='annonceclient',
            options={'verbose_name': 'Annonce client', 'verbose_name_plural': 'Annonces clients'},
        ),
        migrations.RemoveField(
            model_name='annonceclient',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='annonceclient',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='annonceclient',
            name='date_livraison_souhaitee',
        ),
        migrations.RemoveField(
            model_name='annonceclient',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='annonceclient',
            name='volume',
        ),
        migrations.AddField(
            model_name='annonceclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='annonceclient',
            name='date_souhaitee',
            field=models.DateField(blank=True, null=True, verbose_name='Date souhaitée'),
        ),
        migrations.AddField(
            model_name='annonceclient',
            name='heure_souhaitee',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure souhaitée'),
        ),
        migrations.AddField(
            model_name='annonceclient',
            name='prix_propose',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix proposé'),
        ),
        migrations.AddField(
            model_name='annonceclient',
            name='type_annonce',
            field=models.CharField(choices=[('LIVRAISON', 'Livraison de colis'), ('TRANSPORT', 'Transport de personne'), ('SERVICE', 'Service à domicile'), ('ACHAT', "Achat à l'étranger")], default='En cours', max_length=20, verbose_name="Type d'annonce"),
        ),
        migrations.AddField(
            model_name='annonceclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='statut',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ATTRIBUEE', 'Attribuée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='ACTIVE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='titre',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='adresse_arrivee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_arrivee', to='client.adresselivraison'),
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='adresse_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_depart', to='client.adresselivraison'),
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(choices=[('XS', 'Très petit (enveloppe)'), ('S', 'Petit'), ('M', 'Moyen'), ('L', 'Grand'), ('XL', 'Très grand')], max_length=2, verbose_name='Taille')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids (kg)')),
                ('longueur', models.IntegerField(blank=True, null=True, verbose_name='Longueur (cm)')),
                ('largeur', models.IntegerField(blank=True, null=True, verbose_name='Largeur (cm)')),
                ('hauteur', models.IntegerField(blank=True, null=True, verbose_name='Hauteur (cm)')),
                ('contenu', models.TextField(verbose_name='Description du contenu')),
                ('fragile', models.BooleanField(default=False, verbose_name='Colis fragile')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='colis/photos/', verbose_name='Photo du colis')),
                ('instructions_speciales', models.TextField(blank=True, null=True, verbose_name='Instructions spéciales')),
                ('assurance_souhaitee', models.BooleanField(default=False, verbose_name='Assurance souhaitée')),
                ('valeur_declaree', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valeur déclarée (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise à jour')),
                ('annonce', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='client.annonceclient')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
            },
        ),
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('statut', models.CharField(choices=[('ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAIEMENT_CONFIRME', 'Paiement confirmé'), ('EN_PREPARATION', 'En préparation'), ('EN_COURS_LIVRAISON', 'En cours de livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='ATTENTE_PAIEMENT', max_length=20, verbose_name='Statut')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Payment Intent ID')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise à jour')),
                ('adresse_livraison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='client.adresselivraison')),
                ('annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='client.annonceclient')),
            ],
            options={
                'verbose_name': 'Commande client',
                'verbose_name_plural': 'Commandes clients',
            },
        ),
        migrations.CreateModel(
            name='FactureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=20, unique=True, verbose_name='Numéro de facture')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC')),
                ('statut', models.CharField(choices=[('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EMISE', max_length=10, verbose_name='Statut')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/clients/', verbose_name='Fichier PDF')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='client.commandeclient')),
            ],
            options={
                'verbose_name': 'Facture client',
                'verbose_name_plural': 'Factures clients',
            },
        ),
        migrations.CreateModel(
            name='profileClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name='Photo de profil')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('notification_sms', models.BooleanField(default=False, verbose_name='Notifications par SMS')),
                ('notification_push', models.BooleanField(default=True, verbose_name='Notifications push')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise à jour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil client',
                'verbose_name_plural': 'Profils clients',
            },
        ),
        migrations.CreateModel(
            name='EvaluationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='client.commandeclient')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='client.profileclient')),
            ],
            options={
                'verbose_name': 'Évaluation client',
                'verbose_name_plural': 'Évaluations clients',
            },
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='client.profileclient'),
        ),
        migrations.AddField(
            model_name='adresselivraison',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='client.profileclient'),
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='client.profileclient'),
        ),
        migrations.CreateModel(
            name='SuiviColis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PRIS_EN_CHARGE', 'Pris en charge'), ('EN_TRANSIT', 'En transit'), ('EN_ENTREPOT', 'En entrepôt'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('INCIDENT', 'Incident')], max_length=20, verbose_name='Statut')),
                ('date_evenement', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'événement")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('localisation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('photo_preuve', models.ImageField(blank=True, null=True, upload_to='suivi/photos/', verbose_name='Photo preuve')),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_suivi', to='client.colis')),
            ],
            options={
                'verbose_name': 'Suivi de colis',
                'verbose_name_plural': 'Suivis de colis',
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.DeleteModel(
            name='ReservationService',
        ),
    ]
