# Generated by Django 5.1.4 on 2025-06-07 22:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_adresselivraison_alter_annonceclient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresselivraison',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adresselivraison',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Date de mise à jour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='date_souhaitee',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date souhaitée'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='prix_propose',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix proposé'),
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='type_annonce',
            field=models.CharField(choices=[('LIVRAISON', 'Livraison de colis'), ('TRANSPORT', 'Transport de personne'), ('SERVICE', 'Service à domicile'), ('ACHAT', "Achat à l'étranger")], max_length=20, verbose_name="Type d'annonce"),
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Date de mise à jour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Date de mise à jour'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Date de mise à jour'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProfilClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='clients/photos/', verbose_name='Photo de profil')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('notification_sms', models.BooleanField(default=False, verbose_name='Notifications par SMS')),
                ('notification_push', models.BooleanField(default=True, verbose_name='Notifications push')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil client',
                'verbose_name_plural': 'Profils clients',
            },
        ),
        migrations.AlterField(
            model_name='adresselivraison',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='client.profilclient'),
        ),
        migrations.AlterField(
            model_name='annonceclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='client.profilclient'),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='client.profilclient'),
        ),
        migrations.AlterField(
            model_name='evaluationclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='client.profilclient'),
        ),
        migrations.DeleteModel(
            name='profileClient',
        ),
    ]
